version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    expose:
      - 8080
    env_file:
      - .env

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - API_URL=api:8080