version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: me
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    expose:
      - 8080
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000