apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: next-project
spec:
  selector:
    matchLabels:
      app: next-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-app
        image: docker.io/asstra/test
        ports:
          - name: next-app
            containerPort: 3000
            protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: next-project
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
          - name: db
            containerPort: 5432
            protocol: TCP
