apiVersion: v1
kind: Service
metadata:
  name: next-app
  namespace: next-project
spec:
  ports:
  - nodePort: 31001
    port: 3000
    targetPort: 3000
  selector:
    name: next-app
  type: NodePort
