apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: ara-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
        - name: db
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password